name: Cross compile other architectures

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        #arch: [arm-unknown-linux-gnueabihf, armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-gnu, i686-unknown-linux-gnu]
        arch: [aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v2
      - name: prepare build container
        uses: actions-rs/cargo@v1
        run: ci/setup-cross.sh ${{ matrix.arch }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.arch }}
